apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. List the Kubernetes manifests to manage
resources:
  - ../../base

patches:
- path: deployment.yaml
  target:
    kind: Deployment
    name: nginx-frontend
